name: release

on:
  push:
    branches: [master]

jobs:
  release:
    name: release package
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: run semantic-release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN}}
